basePath: /
host: localhost:6000
info:
  contact:
    email: sushrit.pk21@gmail.com
    name: API Support
    url: http://www.localhost:6000/support
  description: This is a sample server for a notification service written in Go.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://localhost:6000/terms/
  title: Go Notification Service API
  version: "1.0"
paths: {}
swagger: "2.0"
